### ISSUE TITLE
Translation publication inquiry

### ISSUE THREAD

**Issue by anemochore** [bt3gl/Python-and-Algorithms-and-Data-Structures#12]
Hi, I work for one of the best IT publishers in Korea. I found your book very helpful. Are you interested in publishing your book to other country?

**Comment by bt3gl** [comment]
Sure, could you give me more details?

**Comment by anemochore** [comment]
Good to hear that! Drop me an email for this. Our copyright manager or agency will contact you.

**Comment by bt3gl** [comment]
bt33gl@gmail.com

**Comment by anemochore** [comment]
Cool! Please be patient. Thank you.
